[package]
name = "transformers_rust"
version = "0.1.0"
authors = ["Ant PC"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.3.1"

[[bin]]
name = "start"
path = "src/main.rs"